name: CI

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          # FTP server name (you may need to specify a port)
          FTP_SERVER: ftp.xfour.co.uk
          # FTP account username
          FTP_USERNAME: autodeploy@utcr.live
          # FTP account password
          FTP_PASSWORD: tO]q-xm*k*?M
          method: ftp
          port: 21
          ARGS: --verbose --transfer-all
